### ISSUE TITLE
Integer overflow on calculating kmer distribution

### ISSUE THREAD

**Issue by sapoudel** [bcgsc/ntCard#48]
Running ntcard sometimes runs into integer overflow. I am not able to figure out why it only breaks sometimes, but it broke on a simple fasta run which I hope can help get to the bottom of it. 

Here is the fasta file (test.fna): 

\>CC8_C10A0
AATGCATACATACAT

\>CC8_C100A0
ATGATGATGATGATG

\>CC8_C100A1
TGATGATGATGATGA

and the command I use is:
 `ntcard -k 5 -o res.txt test.fna`

The output file all contains 9223372036854775808 on the third column. 
![image](https://user-images.githubusercontent.com/30187316/115610634-fe99f580-a29d-11eb-98c8-56e46e378c00.png)

Let me know if you need any other information.

**Comment by kmnip** [comment]
See if using `-c 65535` helps in this case. I think ntCard uses 16-bit integer for its kmer counts.

**Comment by hmohamadi** [comment]
Do you have line-space between your fasta sequences?

**Comment by jowong4** [comment]
Can you tell me what version of ntCard you are using?

**Comment by jowong4** [comment]
@sapoudel I have found the bug and will push it to master branch very soon. I would also like to inform you that when it is fixed all of those 2^63 will become 0 instead of whatever the true frequency of the 33 kmers in your dataset. This is because ntCard samples and it is possible when your dataset is too small, that nothing is sampled based on ntCard's criteria

@hmohamadi  Can you comment on whether you expect ntCard to work as expected with k = 5. The size of the hash set is 4^5 / 2 which is incredibly small. It is possible for nothing to be sampled.

**Comment by sapoudel** [comment]
Thanks for the quick help everyone! The version I am using is 1.2.2

I tried taking out spaces and using -c 65535 and both of them do not work.  @jowong4 might be right. In other toy examples that work with k=5, I get the same error when I drop the k to 2. 

In any case, the example I posted up top was of toy example I was using for testing and development. I was able to run it on my full data and it only ran into this issue with 4 of the 2007 gene clusters with k=36. I only need to estimate k-mer count and that is good enough for me so I am closing the issue. If you want to look further into where this might be breaking, feel free to message me and I can try to dig into the sequences that cause the error.
